name: Bug Report
description: Reportar um bug ou problema
title: "[BUG]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Obrigado por reportar um bug! Por favor, preencha as informações abaixo.

  - type: textarea
    id: description
    attributes:
      label: Descrição do Bug
      description: Descreva claramente o problema encontrado
      placeholder: O sistema retorna erro 500 ao...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Passos para Reproduzir
      description: Como reproduzir o erro?
      placeholder: |
        1. Fazer requisição para...
        2. Com os parâmetros...
        3. Observar erro...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Comportamento Esperado
      description: O que deveria acontecer?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Comportamento Atual
      description: O que realmente acontece?
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Versão
      description: Qual versão está usando?
      placeholder: v1.0.0
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: Ambiente
      options:
        - Development
        - Staging
        - Production
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs Relevantes
      description: Cole logs ou mensagens de erro
      render: shell

  - type: textarea
    id: additional
    attributes:
      label: Informações Adicionais
      description: Qualquer outra informação relevante
