name: Feature Request
description: Sugerir uma nova funcionalidade
title: "[FEATURE]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Obrigado por sugerir uma nova funcionalidade!

  - type: textarea
    id: problem
    attributes:
      label: Problema
      description: Qual problema esta feature resolve?
      placeholder: Atualmente não é possível...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Solução Proposta
      description: Como você imagina que esta feature funcionaria?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternativas Consideradas
      description: Você pensou em outras formas de resolver isso?

  - type: textarea
    id: additional
    attributes:
      label: Contexto Adicional
      description: Mockups, exemplos, links relevantes, etc.
